### ISSUE TITLE
Can't build common-lisp-stat - possible static-vectors issue?

### ISSUE THREAD

**Issue by quicklisp** [sionescu/static-vectors#10]
I'm using sbcl 1.3.13 on Linux amd64.

After `(ql:quickload "cls")` I get this (after a lot of compilation):

    *** Error in `sbcl': malloc(): memory corruption: 0x0000000000678510 ***
    fatal error encountered in SBCL pid 15381(tid 140737353934592):
    SIGABRT received.

    Welcome to LDB, a low-level debugger for the Lisp runtime environment.

**Comment by sionescu** [comment]
Fixed by commit 344bfaecca.
