### ISSUE TITLE
Checking whether an array is a statically allocated

### ISSUE THREAD

**Issue by Shinmera** [sionescu/static-vectors#13]
Is there a way to check whether an array is one that was allocated by static-vectors? I'd like to know this so that I can optimise functions to take a fast-path instead of having to conservatively copy the array to a foreign buffer first.

**Comment by sionescu** [comment]
> Is there a way to check whether an array is one that was allocated by
> static-vectors so that one can know whether it's necessary to call free-static-
> vector on it?
Unfortunately not.

--
Stelian Ionescu a.k.a. fe[nl]ix
Quidquid latine dictum sit, altum videtur.

**Comment by Shinmera** [comment]
Alright, will have to hack a way around that, then.

**Comment by sionescu** [comment]
I can emulate the test using a key-weak hash table, but I'm unsure about the performance effects. I'll have to do some checks.

**Comment by Shinmera** [comment]
That's what I'm doing internally where I'm using static-vectors now, since performance on de/allocation is not that big of a deal to me. I'd be very happy to see the feature in the mainline library though.

**Comment by rpav** [comment]
Is it safe to call `static-vector-pointer` on any vector (without using the result)?  Performance might be better keeping an index of allocated pointers than weak refs.

**Comment by sionescu** [comment]
No, it's not safe.
