### ISSUE TITLE
Add :INITIAL-CONTENTS to WITH-STATIC-VECTOR

### ISSUE THREAD

**Issue by phoe** [sionescu/static-vectors#14]
`MAKE-STATIC-VECTOR` has the `:INITIAL-CONTENTS` key argument, while `WITH-STATIC-VECTORS` does not. I'd like to easily convert a Lisp vector into a static vector to use it within a lexical scope, and such a keyword in `WITH-STATIC-VECTORS` would help me.

**Comment by sionescu** [comment]
Done. Thank you.
