### ISSUE TITLE
quickload failed 

### ISSUE THREAD

**Issue by luoxing91** [sionescu/static-vectors#16]
COMPILE-FILE-ERROR while                                                                                                                                                                    
   compiling #<CL-SOURCE-FILE "cffi-toolchain" "toolchain" "bundle">
   [Condition of type ASDF/FIND-SYSTEM:LOAD-SYSTEM-DEFINITION-ERROR]

Restarts:
 0: [RETRY] Retry compiling #<CL-SOURCE-FILE "cffi-toolchain" "toolchain" "bundle">.
 1: [ACCEPT] Continue, treating compiling #<CL-SOURCE-FILE "cffi-toolchain" "toolchain" "bundle"> as having been successful.
 2: [RETRY] Retry EVAL of current toplevel form.
 3: [CONTINUE] Ignore error and continue loading file "/Users/didi/.roswell/lisp/quicklisp/dists/quicklisp/software/static-vectors-v1.8.3/static-vectors.asd".
 4: [ABORT] Abort loading file "/Users/didi/.roswell/lisp/quicklisp/dists/quicklisp/software/static-vectors-v1.8.3/static-vectors.asd".
 5: [RETRY] Retry ASDF operation.
 --more--

Backtrace:
  0: ((FLET #:HANDLER1452 :IN ASDF/FIND-SYSTEM:LOAD-ASD) #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {1005E3EAD3}>)
  1: (SIGNAL #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {1005E3EAD3}>)
  2: (ERROR UIOP/LISP-BUILD:COMPILE-FILE-ERROR :CONTEXT-FORMAT "~/asdf-action::format-action/" :CONTEXT-ARGUMENTS ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "cffi-$
  3: (UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "cffi-toolchain" "toolchain" "b$
  4: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unavailable argument> #<unavailable argument> #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "cffi-toolchain" "toolchain" "bundle$
  5: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)) #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "cffi-toolchain" "toolchain" "bundle">) [fast-method]
  6: ((:METHOD ASDF/PLAN:PERFORM-PLAN (LIST)) ((#1=#<ASDF/LISP-ACTION:PREPARE-OP > . #2=#<ASDF/SYSTEM:SYSTEM "uiop">) (#3=#<ASDF/LISP-ACTION:COMPILE-OP > . #2#) (#<ASDF/LISP-ACTION:LOAD-OP >$
  7: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
  8: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) ((#1=#<ASDF/LISP-ACTION:PREPARE-OP > . #2=#<ASDF/SYSTEM:SYSTEM "uiop">) (#3=#<ASDF/LISP-ACTION:COMPILE-OP > . #2#) (#<ASDF/LISP-ACTION:LOAD$
  9: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
 10: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1005FBA443}>) [fast-method]
 11: ((:METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "cffi-grovel">) [fast-method]
 12: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "cffi-grovel">)
 13: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
 14: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "cffi-grovel">) [fast-method]
 15: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> ASDF/LISP-ACTION:LOAD-OP #<ASDF/SYSTEM:SYSTEM "cffi-grovel">)
 16: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
 17: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP #<ASDF/SYSTEM:SYSTEM "cffi-grovel">) [fast-method]
 18: (ASDF/OPERATE:LOAD-SYSTEM #<ASDF/SYSTEM:SYSTEM "cffi-grovel">)
 19: (ASDF/OPERATE:LOAD-SYSTEMS* (#<ASDF/SYSTEM:SYSTEM "cffi-grovel">))

**Comment by sionescu** [comment]
This looks like an error in CFFI. Please report it there.
