### ISSUE TITLE
CCL's |memcpy| is often not found

### ISSUE THREAD

**Issue by borodust** [sionescu/static-vectors#17]
Few users report issues with CCL's |memcpy| mappings. But sometimes it just works (I cannot reproduce the issue myself). What could be a possible reason? Would you accept a PR changing |memcpy| usages with CFFI calls?

https://github.com/borodust/trivial-gamekit/issues/31
> SIGNAL Undefined function X86-LINUX64::|memcpy| called with arguments

https://github.com/borodust/hello-gamekit/issues/2
> Error: Undefined function WIN64::|memcpy| called with arguments

https://github.com/borodust/notalone/issues/3
> DEFAULT-UNDEFINED-FUNCTION-CALL-RESTARTS 10242206 X86-DARWIN64::|memcpy|

**Comment by 3b** [comment]
also got `Error: Foreign function not found: WIN64::|memset|` on `Clozure Common Lisp Version 1.11.5/v1.11.5  (WindowsX8664)`, windows 8.1

**Comment by sionescu** [comment]
I think this should be reported upstream because I've had other reports where the released binaries worked, but recompiling CCL triggered this failure.

**Comment by sionescu** [comment]
Sure, a patch that uses cffi:foreign-funcall is OK for me.

**Comment by 3b** [comment]
Seems like my problem was a bad install of ccl, was missing the `win64-headers/` directory which the "#_" apparently needs to find the functions.

**Comment by sionescu** [comment]
@borodust can you also check if the headers were present in those bug reports ?
