### ISSUE TITLE
Do static vectors survive image saving?

### ISSUE THREAD

**Issue by phoe** [sionescu/static-vectors#18]
I want to allocate a static vector and save a Lisp image, for example, via SBCL's `SAVE-LISP-AND-DIE`. Can I expect the static vector to still be there after the resulting Lisp image is booted up, or do I need to always reinitialize it after the image is booted?

**Comment by stassats** [comment]
sb-int:make-static-vector is using sbcl memory, not foreign memory or anything like that. It will persist in a saved core.

**Comment by sionescu** [comment]
No you shouldn't expect that. The current SBCL implementation uses foreign memory, not sb-int:make-static-vector, so you always need to reallocate them on image start.
