### ISSUE TITLE
Q: Use existing foreign vectors in CL?

### ISSUE THREAD

**Issue by phmarek** [sionescu/static-vectors#21]
Is there a way to represent externally allocated data as a (typed) vector in CL?

ie. I've got a SAP, the type, and a length (bytes or number of elements) - can I get a `VECTOR` pointing to the same data?

The only way I know right now is to use `CL21` and to provide a new class and methods on `AREF` - but that isn't compatible with already existing code.

**Comment by sionescu** [comment]
What you describe is an array displaced to a SAP, where the header is allocated in the Lisp heap, but the data is in foreign memory. AFAIK, that is only possible on Allegro.
