### ISSUE TITLE
Breaking changes for SBCL 2.0.1

### ISSUE THREAD

**Issue by mfiano** [sionescu/static-vectors#22]
Some internal items were removed from `*features*` with SBCL 2.0.1, causing `static-vectors` to fail to compile:
```
; caught WARNING:
;   :LINKAGE-TABLE is no longer present in *FEATURES*
```
and ultimately `Error while trying to load definition for system static-vectors`

**Comment by sionescu** [comment]
I believe that was caused by CFFI.
