### ISSUE TITLE
Declaring a type.

### ISSUE THREAD

**Issue by commander-trashdin** [sionescu/static-vectors#24]
Not sure how much of an issue is this but it seems none of the exported macros declare the created static vector type. Do I need to declare it myself? Is it even necessary? Need clarification one that matter, thanks in advance.

**Comment by sionescu** [comment]
There is no separate static-vector type because these vectors are basically indistinguishable from regular vectors.

**Comment by commander-trashdin** [comment]
Okay got it. But do I have to declare the type myself (for optimization purposes) or is it unnecessary? Also, is it vector/simple-vector/simple-array?

**Comment by sionescu** [comment]
It's just simple-array.

**Comment by commander-trashdin** [comment]
I see, so (declare (type (simple-array size element-type) var)), where type and size are the same as specified in macro? (Otherwise might be UB I suppose)

**Comment by sionescu** [comment]
I pushed a series of changes which ensure that WITH-STATIC-VECTOR correctly declares the array type.
