### ISSUE TITLE
Feature request: automatic dealocation through finalizer

### ISSUE THREAD

**Issue by ghost** [sionescu/static-vectors#3]
Maybe the task of freeing the underlying memory for a static-vector could be delegated to a finalizer?
 
Right now that's probably not possible for the user because free-static-vector() takes the vector object as argument, so calling this from a finalizer wouldn't work as far as I see it.
  
Maybe the user could be given a choice?  I'm thinking about something  like an additional keyword argument (:finializep) passed to  make-static-vector() in which case a finializer is installed which frees the underlying foreign memory automatically.  In this case the user doesn't need to  call free-static-vector().  Of course the two mechanisms would be mutual exclusive and backward compatibiliy would be given.

**Comment by sionescu** [comment]
Finalizers aren't guaranteed to work across implementations.
