### ISSUE TITLE
Portable free-static-vector using trivial-garbage

### ISSUE THREAD

**Issue by digikar99** [sionescu/static-vectors#30]
As I understand currently, it should be possible to implement a reliable `free-static-vector` using trivial-garbage following [the example in the SBCL Manual](http://www.sbcl.org/manual/#Garbage-Collection). Is it not done to keep things bare-bones and avoid any performance penalties - or should I (or someone) go forward with attempting this and issue a PR?

**Comment by sionescu** [comment]
On SBCL the static vectors are outside the Lisp heap so they won't be garbage-collected, which means that finalizers will never be invoked.

**Comment by digikar99** [comment]
Okay, looking into the internals a bit, it looks as if the pointer and address objects are freshly created on each call to `static-vector-address/pointer`, so there is no notion of "inbuilt handle that could be garbage collected". My best bet seems to be to store the static-vector-address in a wrapper array object, and call `finalize` on this wrapper object. (For my purposes, the wrapper array object is anyways required, so, not much overhead.)

Thanks!
