### ISSUE TITLE
static-vectors confuses SBCL errors

### ISSUE THREAD

**Issue by 3b** [sionescu/static-vectors#4]
in the following code:

```Lisp
(defun foo (a)
  (static-vectors:with-static-vector (p a )
    (setf (aref p a) 1)))
(foo 123)
```

SBCL gives the error

```
The value #<invalid object #x6EEF1F> is not of type ARRAY.
```

instead of the expected

```
Index 123 out of bounds for (SIMPLE-ARRAY (UNSIGNED-BYTE 8) (123)), should be nonnegative and <123.
```
[discussion in #sbcl](http://ccl.clozure.com/irc-logs/sbcl/2015-02/sbcl-2015.02.08.txt) suggests part of the problem is that static-vectors may be allocating more than it needs to in foreign memory, which confuses the debugger when it expects to only see objects on the lisp heap.

**Comment by sionescu** [comment]
The SBCL is a hack that works pretty well, but I'm not surprised that the debugger can't deal with this case.
