### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by rabbibotton** [sionescu/static-vectors#40]
[package static-vectors].; gcc -o "C:\Users\david\AppData\Local\cache\common-lisp\sbcl-2.4.4-win-x64\C\Users\david\work\clog-win64-ez\quicklisp\dists\ultralisp\software\sionescu-static-vectors-20240531082431\src\ffi-types__grovel-tmpD80C1I1S.obj" -c -m64 -IC:/Users/david/work/clog-win64-ez/quicklisp/dists/quicklisp/software/cffi-20231021-git/ "C:\Users\david\AppData\Local\cache\common-lisp\sbcl-2.4.4-win-x64\C\Users\david\work\clog-win64-ez\quicklisp\dists\ultralisp\software\sionescu-static-vectors-20240531082431\src\ffi-types__grovel.c"

debugger invoked on a CFFI-GROVEL:GROVEL-ERROR in thread #<THREAD tid=64744 "main thread" RUNNING {1000B98003}>: Couldn't execute "gcc": The system cannot find the file specified.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry #<PROCESS-OP > on #<GROVEL-FILE "static-vectors" "ffi-types">.
  1: [ACCEPT                       ] Continue, treating #<PROCESS-OP > on #<GROVEL-FILE "static-vectors" "ffi-types"> as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the configuration.
  4:                                 Retry ASDF operation.
  5:                                 Retry ASDF operation after resetting the configuration.
  6: [ABORT                        ] Give up on "clog"
  7: [REGISTER-LOCAL-PROJECTS      ] Register local projects and try again.
  8: [CONTINUE                     ] Ignore runtime option --eval "(ql:quickload :clog)".
  9:                                 Skip rest of --eval and --load options.
 10:                                 Skip to toplevel READ/EVAL/PRINT loop.
 11: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(CFFI-GROVEL:GROVEL-ERROR "~a" #<SIMPLE-ERROR "Couldn't execute ~S: ~A" {10062C2AE3}>)
   source: (ERROR (QUOTE GROVEL-ERROR) :FORMAT-CONTROL FORMAT-CONTROL :FORMAT-ARGUMENTS FORMAT-ARGUMENTS)
0]

**Comment by sionescu** [comment]
Hy @rabbibotton, you presumably need to install mingw or some other version of gcc. I don't use Windows, so I can't help you there.

**Comment by rabbibotton** [comment]
That is not possible. This showed up in last days I suspect someone started to include you project as a dependency in UltraLisp just recently

**Comment by rabbibotton** [comment]
Not possible meaning not possible for me to add that to this build environment

**Comment by rabbibotton** [comment]
You are a dependency of fast-io since 4 years ago, so looks like it is your library's change in the last week

**Comment by rabbibotton** [comment]
I git back to a previews commit 87a447a8eaef9cf4fd1c16d407a49f9adaf8adad and your project works on Windows

**Comment by rabbibotton** [comment]
I git forward now and can confirm your recent changes break on Windows - this means your change is break for tons of projects if run on Windows, please consider fixing

**Comment by sionescu** [comment]
Check the latest commit.
