### ISSUE TITLE
ECL on linux failure 

### ISSUE THREAD

**Issue by rabbibotton** [sionescu/static-vectors#41]
;;; Loading "/home/dbotton/.quicklisp/setup.lisp"
;;; Loading #P"/usr/lib/x86_64-linux-gnu/ecl-21.2.1/asdf.fas"
To load "clog/tools":
  Load 1 ASDF system:
    clog/tools
; Loading "clog/tools"
An error occurred during initialization:
Error while trying to load definition for system static-vectors from pathname /home/dbotton/.quicklisp/dists/ultralisp/software/sionescu-static-vectors-20240531082431/static-vectors.asd: don't recognize component type :CFFI-GROVEL-FILE.

BTW this is the key issue on Windows too the commit "allocation alignment" was working on windows the issue was the next commit "[Use size_t for the FFI call to posix_memalign()](https://github.com/sionescu/static-vectors/commit/a4b2c1623989db67be7e123bbd52f583e88a66e7)"

**Comment by sionescu** [comment]
Thanks, fixed.
