### ISSUE TITLE
Cannot load from Quicklisp on CCL x86-64 Linux

### ISSUE THREAD

**Issue by helmutkian** [sionescu/static-vectors#43]
On x86-64 Linux with CCL v1.13 `#<SYSTEM static-vectors / static-vectors-v1.9.3 / quicklisp 2024-10-12>` cannot be loaded.

Attempting `(ql:quickload 'static-vectors)` results in:

```Error: Foreign function not found: X86-LINUX64::|memset|```

**Comment by sionescu** [comment]
Try deleting all fasls and trying again, updating CCL or reporting this to CCL upstream. the function `memset` exists and I can't reproduce the error.
